### ISSUE TITLE
Access graphs per URL

### ISSUE THREAD

**Issue by tombu** [stravid/hulkort#31]
In order to see the commit graph of a certain repository
As a visitor
I can access the graph through a URL

**Comment by stravid** [comment]
Should the graph be an image?

**Comment by stravid** [comment]
And how do we approach the unique URL? I guess it should be an hash, but we have to figure out how to program something like this.

**Comment by tombu** [comment]
An image seems to be the nicest way for the client, doesn´t it?
Although for us this means generating the images in the backend.

other formats:
- html: like wie use on our pages OR a canvas
- json: I have no idea how that should work
- ?

Further details about the unique URL should be discussed. A hash is what I thought of, too.

**Comment by stravid** [comment]
Does this look like what we need? https://github.com/paulca/shortcode-url
Maybe search for other solutions to have a comparison :-)

I thought about this: A repository (does it have a name btw.?) has a shortcode. When calling hulkort.com/graphs/abc123 it will generate the graph for repository abc123. Is there a way to support different types of graphs? Do we want this? How can we accomplish this?

**Comment by tombu** [comment]
A lot to discuss again. I prefer another place for doing this, e.g. campfire, voice!

**Comment by stravid** [comment]
Things got a lot easier! Talked with Justin, a public HTML page is good! So no need for image rendering / s3 :-) Although I'm also a little sad haha

**Comment by tombu** [comment]
:( me, too.
Maybe a prospective feature ;)
