### ISSUE TITLE
Add a commit to a specific repository

### ISSUE THREAD

**Issue by stravid** [stravid/hulkort#34]
In order to organize my commit stats
As a API client
I want to post to specific repository

**Comment by stravid** [comment]
API call should be the same like before, but you can add a repository parameter: &repository=1

**Comment by stravid** [comment]
What do we do with existing commits and commits where no repository is specified? A default repository for every user? Or is it okay that a commit doesn't belong to a repository?

**Comment by tombu** [comment]
No repository - should be o.k. 

I just realized: With this feature every 'normal' user will be able to track his commits per repository by using repository specific commit hooks. ;)

**Comment by stravid** [comment]
Good!

Yes that's true, but rather complicated to do so, you have to edit the hook for each repository by hand. Atleast I can't think of an automatic solution with Git templates.
