### ISSUE TITLE
hulkort.com Domain

### ISSUE THREAD

**Issue by stravid** [stravid/hulkort#35]
Should we get it? If yes, how do we approach the switch from the Heroku URL to our costum one?

**Comment by tombu** [comment]
I´m not so sure about it. Would be really nice but we have spend money that probably doesn´t come back.
Switching form the Heroku URL to a custom one shouldn´t be a problem. The Heroku one will still work, won´t it? There would be no need to change the URL in the post-commit hooks (or elsewhere).

**Comment by stravid** [comment]
Yeah I thought the same, shouldn't be a problem. And guys going to the heroku url can be redirected.

Yes maybe we won't get back the 12 euro, don't know if a "nice" domain is worth 12 euro?

**Comment by tombu** [comment]
Do it!
